### ISSUE TITLE
can  not start ?

### ISSUE THREAD

**Issue by urmyfaith** [LancasterSolutions/docker-apachephp7#10]
➜  ~ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
quantafuture/docker-apachephp7   latest              5ce3c00555f9        2 weeks ago         787.7 MB
➜  ~ docker run -it quantafuture/docker-apachephp7
[Sat Jan 07 03:09:10.044419 2017] [core:warn] [pid 1] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Sat Jan 07 03:09:10.069034 2017] [core:warn] [pid 1] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Sat Jan 07 03:09:10.082387 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.1.0 OpenSSL/1.0.1t configured -- resuming normal operations
[Sat Jan 07 03:09:10.082428 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Sat Jan 07 03:09:10.974614 2017] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
➜  ~

**Comment by JanisGruzis** [comment]
Hello. Thank you for contribution.

This is expected behavior if you run apache in foreground and do terminal resize. What happens is terminal sends signal to its foreground application on resize so that it can resize for example UI. But apache team has special implementation for this signal - `SIGWINCH.` For details please visit apache issue report - [https://bz.apache.org/bugzilla/show_bug.cgi?id=50669](https://bz.apache.org/bugzilla/show_bug.cgi?id=50669)

This can be reproduced by running

1. `docker run -it quantafuture/docker-apachephp7`
2. resize your terminal (this can be OS/terminal vendor specific)

But this is not really an issue because:

1. This is implementation of apache team.
2. Apache should be run as foreground application only for debugging purposes. What `docker run -it` command does is runs it in foreground and with "-it" part redirects input and signals to docker container.

To avoid this issue we suggest you to use docker-compose or run your container as daemon:

1. `docker run -d quantafuture/docker-apachephp7`
2. `docker logs -f <container ID you get from first command>`

**Comment by salimdawod1996** [comment]
> Hello. Thank you for contribution.
> 
> This is expected behavior if you run apache in foreground and do terminal resize. What happens is terminal sends signal to its foreground application on resize so that it can resize for example UI. But apache team has special implementation for this signal - `SIGWINCH.` For details please visit apache issue report - https://bz.apache.org/bugzilla/show_bug.cgi?id=50669
> 
> This can be reproduced by running
> 
>     1. `docker run -it quantafuture/docker-apachephp7`
> 
>     2. resize your terminal (this can be OS/terminal vendor specific)
> 
> 
> But this is not really an issue because:
> 
>     1. This is implementation of apache team.
> 
>     2. Apache should be run as foreground application only for debugging purposes. What `docker run -it` command does is runs it in foreground and with "-it" part redirects input and signals to docker container.
> 
> 
> To avoid this issue we suggest you to use docker-compose or run your container as daemon:
> 
>     1. `docker run -d quantafuture/docker-apachephp7`
> 
>     2. `docker logs -f <container ID you get from first command>`
> 
>     3. `docker stop <container ID you get from first command>`

Great! thanks bro
